### ISSUE TITLE
Fix `set-output` since it is deprecated

### ISSUE THREAD

**Issue by anovis** [goblet/goblet-github-actions#17]
--
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/Show less
 

<br class="Apple-interchange-newline">

**Comment by diegoandresdiazespinoza** [comment]
More information link is in [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
